interfaces:
  anemone:
    name: Anemone Dashboard
    description: First newly developed analysis dashboard
    default_problem: opal
    final: yes
  begonia:
    name: Begonia Dashboard
    description: Medical image analysis dashboard
    default_problem: tanzanite
    final: no
  calla:
    name: Calla Dashboard
    description: Credit risk assessment dashboard
    default_problem: prasiolite
    final: no
  dalia:
    name: Dalia Dashboard
    description: Sentiment analysis dashboard
    default_problem: ruby
    final: no
  erica:
    name: Erica Dashboard
    description: Fraud detection dashboard
    default_problem: sodalite
    final: no

problems:
  opal:
    name: Personal finance
    description: Binary classification problem for predicting personal loan approval
    final: yes
  prasiolite:
    name: Prasiolite
    description: Regression analysis
    final: no
  ruby:
    name: Ruby
    description: Natural language processing
    final: no
  sodalite:
    name: Sodalite
    description: Anomaly detection
    final: no
  tanzanite:
    name: Tanzanite
    description: Image recognition
    final: no

# Optional: define valid combinations
valid_combinations:
  anemone:
    problems: [opal, prasiolite, sodalite]
    final: no
  begonia:
    problems: [tanzanite, ruby]
    final: no
  calla:
    problems: [prasiolite, opal, sodalite]
    final: no
  dalia:
    problems: [ruby, opal]
    final: no
  erica:
    problems: [sodalite, prasiolite, opal]
    final: no

tech:
  client:
    port: 5001
  server:
    port: 5010
