problem:
  id: opal
  type: classification
  target: loan_granted

features:
  # Feature definitions with types, ranges, descriptions
  loan_id:
    type: int
    min: 1
    max: 4269
    description: Unique identifier for each loan
    explorable: no
  no_of_dependents:
    type: int
    min: 0
    max: 5
    description: Number of dependents of the applicant
    explorable: no
  education:
    type: categorical
    options: ["Not Graduate", "Graduate"]
    description: Formal education of the applicant
    explorable: yes
  self_employed:
    type: bool
    description: Employment status of the applicant
    explorable: yes
  income_annum:
    type: float
    min: 0
    max: 9900000
    description: Annual income of the applicant
    explorable: yes
  loan_amount:
    type: float
    min: 100
    max: 395000000
    description: Amount of loan requested
    explorable: yes
  loan_term:
    type: int
    min: 2
    max: 20
    description: Duration of the loan in years
    explorable: yes
  cibil_score:
    type: int
    min: 300
    max: 900
    description: Credit score of the applicant
    explorable: no
  residential_assets_value:
    type: float
    min: -100000
    max: 29100000
    description: Value of residential assets owned by the applicant
    explorable: no
  commercial_assets_value:
    type: float
    min: 0
    max: 19400000
    description: Value of commercial assets owned by the applicant
    explorable: no

model:
  type: "random_forest"
  version: "1.2.3"
  accuracy: 0.87
  path: "models/random_forest_v1.2.3.pkl"
