problem:
  name: "Personal finance"
  type: "Classification"
  description: "Binary classification problem for predicting concession of a personal loan"

features:
  # Feature definitions with types, ranges, descriptions
  name:
    type: str
    min: 0.0
    max: 200.0
    description: Monthly charges in dollars
  age:
    type: int
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  income:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  credit_score:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  loan_amount:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  defaulted:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  marital_status:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  education_level:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract
  employment_status:
    type: categorical
    options: ["Month-to-month", "One year", "Two year"]
    description: Length of customer contract


model:
  type: "random_forest"
  version: "1.2.3"
  accuracy: 0.87
  path: "models/random_forest_v1.2.3.pkl"
